---
- hosts: windows9Server64Guest
  
  tasks:
  - name: enable RDP
    win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      value: 0
  - name: enable firewall
    win_firewall:
      state: enabled
  - name: Firewall rule to allow RDP on TCP port 3389
    win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
