---
- hosts: windows2016
  serial: 1

  tasks:
  - win_dsc:
      resource_name: xADGroup
      Ensure: present
      GroupName: "vm-{{inventory_hostname}}"
      Path: "OU=grp,DC=ad,DC=maxdepth,DC=io"
    delegate_to: dc


- hosts: windows2016
  vars_files:
    - vars/domain.yml

  tasks:
  - name: dns servers
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses: 10.0.0.11

  - name: set timezone
    win_timezone:
      timezone: Eastern Standard Time

  - name: enable firewall
    win_firewall: state=enabled

  - name: enable RDP
    win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      value: 0

  - name: allow RDP
    win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

  - name: domain membership
    win_domain_membership:
      dns_domain_name: "{{ domain_name }}"
      domain_admin_user: "{{ domain_admin }}@{{ domain_name }}"
      domain_admin_password: "{{ domain_pass }}"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required

  - win_group_membership:
      name: Administrators
      members: "{{ local_admins }}"
      state: present
    when: local_admins is defined
    register: result
    failed_when: "result.msg is defined and 'already' not in result.msg"

  - name: group apps
    win_chocolatey:
      name: '{{ item }}'
      state: latest
    with_items: '{{ group_apps }}'
    when: group_apps is defined

  - name: host apps
    win_chocolatey:
      name: '{{ item }}'
      state: latest
    with_items: '{{ host_apps }}'
    when: host_apps is defined
