---
- hosts: windows2016
  vars_files:
    - vars/domain.yml

  tasks:
  - name: dns servers
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses: 10.0.0.11
  - name: set timezone
    win_timezone:
      timezone: Eastern Standard Time
  - name: enable firewall
    win_firewall: state=enabled
  - name: enable RDP
    win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      value: 0
  - name: allow RDP
    win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
  - name: domain membership
    win_domain_membership:
      dns_domain_name: "{{ domain_name }}"
      domain_admin_user: "{{ domain_admin }}@{{ domain_name }}"
      domain_admin_password: "{{ domain_pass }}"
      state: domain
    register: domain_state
  - win_reboot:
    when: domain_state.reboot_required
  - win_group_membership:
      name: Administrators
      members: "{{ local_admins }}"
      state: present
    when: local_admins is defined
    register: result
    failed_when: "result.msg is defined and 'already' not in result.msg"
  - name: ensure common tools are installed
    win_chocolatey:
      name: '{{ item }}'
    with_items: ['sysinternals', 'googlechrome']
