---
- hosts: windows9Server64Guest
  vars_files:
    - vars/domain.yml 
 
  tasks:
  - win_dns_client:
    adapter_names: "*"
    ipv4_addresses: 10.0.0.11
  - name: enable RDP
    win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      value: 0
  - name: Firewall rule to allow RDP on TCP port 3389
    win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
  - win_domain_membership:
      dns_domain_name: ad.mod.local 
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ domain_pass }}"
      state: domain
    register: domain_state
  - win_reboot:
    when: domain_state.reboot_required
